### PR TITLE
Add blog to site

### PR DESCRIPTION
**Pull request by johnmccabe**
This PR migrates the static landing page to Jekyll, and introduces a blog using a modified CloudCannon/frisco-jekyll-template template.

Publishing the site can be handled using github pages for simplicity, you can see a live site here:

- https://johnmccabe.net/www/

## TODO
- [ ] Update readme with instructions on running locally (`bundle install`/`bundle exec jekyll serve`)
- [ ] Update readme with instructions/guidelines on adding a new post (its pretty obvious from the example)
- [ ] Update readme with instructions/guidelines on adding a new author (its pretty obvious from the example)
- [ ] Setup site generation/publishing, @alexellis you'll need to do this

### CODE REVIEW

**Comment by johnmccabe** [comment]
@alexellis that should address the sizing issues you'd observed on mobile, I've switched from the hacked css to sass for the old landing page integration (the styling of the landing page should be pretty much identical to the original now as well).

Also adds the Docs link to the header and footer.

**Comment by johnmccabe** [comment]
Related PR openfaas/faas#761

**Comment by johnmccabe** [comment]
@alexellis just for clarity, I'll update the README with usage instructions when I get the 👍 on the styling.

**Comment by alexellis** [comment]
The page is much better on mobile now. Thank you.

Can you send the visuals question here?

Alex

**Comment by johnmccabe** [comment]
There are two outstanding questions from slack:

### New Dark Blue
Need to decide what to replace the old blue gradient on the landing page with - keeping the overall styling close to the original (wave etc).

You'd shared this image on slack as representative of the new darker blue:

Darker blue

And I proposed the following suggestions.

A - Solid blue

image

B - Gradient 1

image

C - Gradient 2

image

D - Gradient 3

image


My personal preferences being options A or D.

### URL Format

The current format mirrors how you've configured your personal blog where the URL for a post is:

    https://<domain>/<blog-title>

I like the simplicity/portability of this format.

You'd asked about the option of including tags in the URL, for example:

    https:////<domain>/<tag1>/<tag2>/<blog-title>

Which is also feasible (its just a configuration option in `_config.yml`) - see [here](https://jekyllrb.com/docs/permalinks/) (tags are called categories in Jekyll).

This is a decision you want to make **once**, as switching between post permalink formats is undesirable from an SEO point of view.

**Comment by johnmccabe** [comment]
I think the other issue around adding a logo carousel should be handled in a PR rather than introduce creep here.

**Comment by alexellis** [comment]
I don't think that was the newer dark blue, it was the one used in the new keynote template.

screen shot 2018-06-20 at 4 49 43 pm

**Comment by alexellis** [comment]
They all look nice though and I like the gradient.

**Comment by alexellis** [comment]
My blog on Ghost supports tags and permalinks i.e.

https://blog.alexellis.io/introducing-the-openfaas-operator/
https://blog.alexellis.io/tag/crd/

**Comment by johnmccabe** [comment]
The post permalink is the https://blog.alexellis.io/introducing-the-openfaas-operator/, ie the URL that will get indexed by Google etc, the tags links are just for organisation - https://blog.alexellis.io/tag/crd/.

The equivalent for a tag page is the category page, should be straightforward to add back.

**Comment by alexellis** [comment]
Please use the last but one gradient.

**Comment by alexellis** [comment]
(Changed my mind again - please use the solid colour)

**Pull request merged**
